# .goreleaser.yml
# Build customization
project_name: bin-echo 
builds:
  - main: ./main.go
    binary: bin-echo
    env:
      - CGO_ENABLED=0
    asmflags:
      - all=-trimpath={{ .Env.PWD }}
    gcflags:
      - all=-trimpath={{ .Env.PWD }}
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: freebsd
        goarch: 386
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: ppc64le
      - goos: freebsd
        goarch: s390x
      - goos: windows 
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: s390x
# Archive customization
archive:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  format: zip
  format_overrides:
    - goos: linux 
      format: tar.gz
  files:
    - none*
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"
release:
  name_template: "{{ .ProjectName }}-v{{ .Version }}"
  github:
    owner: computes
    name: help
dockers:
  - 
    dockerfile: Dockerfile.goreleaser
    image: computes/bin-echo-386
    binary: bin-echo
    goos: linux
    goarch: 386
    tag_templates:
      - "v{{ .Version }}"
      - latest
  - 
    dockerfile: Dockerfile.goreleaser
    image: computes/bin-echo-amd64
    binary: bin-echo
    goos: linux
    goarch: amd64
    tag_templates:
      - "v{{ .Version }}"
      - latest
  - 
    dockerfile: Dockerfile.goreleaser
    image: computes/bin-echo-armv7
    binary: bin-echo
    goos: linux
    goarch: arm
    goarm: 7
    tag_templates:
      - "v{{ .Version }}"
      - latest
  - 
    dockerfile: Dockerfile.goreleaser
    image: computes/bin-echo-armv6
    binary: bin-echo
    goos: linux
    goarch: arm
    goarm: 6
    tag_templates:
      - "v{{ .Version }}"
      - latest
  - 
    dockerfile: Dockerfile.goreleaser
    image: computes/bin-echo-arm64
    binary: bin-echo
    goos: linux
    goarch: arm64
    tag_templates:
      - "v{{ .Version }}"
      - latest
  - 
    dockerfile: Dockerfile.goreleaser
    image: computes/bin-echo-ppc64le
    binary: bin-echo
    goos: linux
    goarch: ppc64le
    tag_templates:
      - "v{{ .Version }}"
      - latest
  - 
    dockerfile: Dockerfile.goreleaser
    image: computes/bin-echo-s390x
    binary: bin-echo
    goos: linux
    goarch: s390x
    tag_templates:
      - "v{{ .Version }}"
      - latest
  - 
    dockerfile: Dockerfile.goreleaser
    image: computes/bin-echo-freebsd
    binary: bin-echo
    goos: freebsd
    goarch: amd64
    tag_templates:
      - "v{{ .Version }}"
      - latest
